
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

from pandas import DataFrame
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from numpy import loadtxt, where
# scale larger positive and values to between -1,1 depending on the largest
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-1,1))


dataFrame = pd.read_csv('bank.csv',sep=';',index_col = None, header = None)
X = dataFrame.iloc[:,:-1].values
Y = dataFrame.iloc[:,16].values

labelencode = LabelEncoder()
X[:,1] = labelencode.fit_transform(X[:,1])
X[:,2] = labelencode.fit_transform(X[:,2])
X[:,3] = labelencode.fit_transform(X[:,3])
X[:,4] = labelencode.fit_transform(X[:,4])
X[:,6] = labelencode.fit_transform(X[:,6])
X[:,7] = labelencode.fit_transform(X[:,7])
X[:,8] = labelencode.fit_transform(X[:,8])
X[:,15] = labelencode.fit_transform(X[:,15])
Y = labelencode.fit_transform(Y)

X = np.delete(X, np.s_[9:11], 1)
X = np.array(X)
X = X.astype(np.float)
X = min_max_scaler.fit_transform(X)
Y = np.array(Y)


#fit remaining categorical columns and then try one hot encoding 



# creating testing and training set
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33)

# train scikit learn model 
clf = LogisticRegression()
clf.fit(X_train,Y_train)
print 'score Scikit learn: ', clf.score(X_test,Y_test)


##The sigmoid function adjusts the cost function hypotheses to adjust the algorithm proportionally for worse estimations
def Sigmoid2(z):
	z_matrix = []
	for x in np.nditer(z):
		G_of_Z = float(1.0 / float((1.0 + math.exp(-1.0*x))))
		z_matrix.append(G_of_Z)
	npa = np.matrix(z_matrix, dtype=np.float32)
	return npa.T

def Sigmoid(z):
	G_of_Z = float(1.0 / float((1.0 + math.exp(-1.0*z))))
	return G_of_Z



def Hypothesis(theta, x):
	z = 0
	theta = np.matrix(theta)
	theta_trans = np.transpose(theta)
	X = np.matrix(x)
	z = np.dot(X,theta_trans)

	return Sigmoid(z)

def Hypothesis2(theta, x):
	z = 0
	theta_trans = np.matrix(theta).T 
	z = np.dot(x, theta_trans)
	return Sigmoid2(z)


def Cost_Function(X,Y,theta,m):
	sumOfErrors = 0
	theta = np.array(theta)
	Y = Y.T
	for i in xrange(m):
		xi = X[i]
		hi = Hypothesis(theta,xi)
		
		if Y[i] == 1:
			error = Y[i] * math.log(hi)
		elif Y[i] == 0:
			error = (1-Y[i]) * math.log(1-hi)
		sumOfErrors += error
	const = -1/m
	J = const * sumOfErrors
	print 'cost is ', J 
	return J

##This function creates the gradient component for each Theta value 
def Cost_Function_Derivative(X,Y,theta,m,alpha):
	sumErrors = 0
	hi = Hypothesis2(theta,X)
	hi_subtract = np.subtract(hi,Y.T)
	error = np.dot(hi_subtract.T, X)
	m = len(Y)
	constant = float(alpha)/float(m)
	J = np.multiply(constant,error)
	return error

def Gradient_Descent(X,Y,theta,m,alpha):
	constant = alpha/m
	theta = np.matrix(theta)
	CFDerivative = Cost_Function_Derivative(X,Y,theta,m,alpha)
	CFDerivative = np.multiply(constant,CFDerivative)
	new_theta = np.subtract(theta,CFDerivative)
	return new_theta


def Logistic_Regression(X,Y,alpha,theta,num_iters):
	m = len(X)
	X = np.matrix(X)
	Y = np.matrix(Y)
	for x in xrange(num_iters):
		new_theta = Gradient_Descent(X,Y,theta,m,alpha)
		theta = new_theta
		if x % 100 == 0:
			#here the cost function is used to present the final hypothesis of the model in the same form for each gradient-step iteration
			Cost_Function(X,Y,theta,m)
			print 'theta ', theta
			print 'cost is ', Cost_Function(X,Y,theta,m)
	Declare_Winner(theta)

##This method compares the accuracy of the model generated by the scikit library with the model generated by this implementation
def Declare_Winner(theta):
	score = 0
	winner = ""
	scikit_score = clf.score(X_test,Y_test)
	length = len(X_test)
	for i in xrange(length):
	 	prediction = round(Hypothesis(X_test[i],theta))
		answer = Y_test[i]
		if prediction == answer:
			score += 1
	my_score = float(score) / float(length)
	print 'Your score: ', my_score
	print 'Scikits score: ', scikit_score 


initial_theta = np.zeros(14)  #[0,0] 
alpha = 0.1
iterations = 1000
Logistic_Regression(X_train,Y_train,alpha,initial_theta,iterations)